name: Java CI with Maven

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 and Maven for the project
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: mvn install

      # Step 4: Run all tests
      - name: Run tests
        run: mvn test -Ddataproviderthreadcount=1

      # Step 5: Upload the Extent Report as an artifact
      - name: Upload Extent Reports
        if: always() # Always upload the report, even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: target/ExtentReport.html
